check kubectl installation.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -82,6 +82,12 @@ jobs:
       - run:
           name: Creating the EKS cluster.
           command: |
+            kubectl version --short --client
+            if [ "$?" -ne 0 ]
+            then
+                echo "Kubectl not found"
+                exit 1
+            fi
             eksctl create cluster --name e-capstone-${CIRCLE_WORKFLOW_ID:0:7} --fargate --asg-access
             kubectl get nodes
             pwd && ls -la
@@ -124,13 +130,17 @@ workflows:
       - deploy_eks_cluster:
           requires:
             - "build"
+      - create-deployment:
+          cluster-name: eks-demo-deployment
+          requires:
+            - "deploy_eks_cluster"
       - aws-eks/update-container-image:
           cluster-name: e-capstone-${CIRCLE_WORKFLOW_ID:0:7}
           resource-name: "e-capstone"
           container-image-updates: "e-capstone=e-capstone-${CIRCLE_WORKFLOW_ID:0:7}"
           record: true
           requires:
-            - "deploy_eks_cluster"
+            - "create-deployment"
 
 
 # aws eks update-kubeconfig --region us-west-2 --name help --kubeconfig config-2
